esphome:
  name: esp01-dehumidifier
  friendly_name: esp01-dehumidifier
  on_boot:
    priority: -10
    then:
      - delay: 10s  # Wait for the device to initialize properly
      - select.set:
          id: fan_mode_select
          option: "Low"

esp8266:
  board: esp01_1m

# Enable logging
logger:
  baud_rate: 0

# Enable Home Assistant API
api:
  encryption:
    key: "<TODO>"

ota:
  password: "<TODO>"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: LIGHT


  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp01-Dehumidifier"
    password: "<TODO>"

web_server:
  port: 8080
  auth:
    username: !secret web_server_username
    password: !secret web_server_password

mqtt:
  broker: <TODO>
  username: mqtt
  password: !secret mqtt_password
  
  topic_prefix: esp/$devicename
  discovery_object_id_generator: device_name
  
  will_message:
    topic: status
    payload: 

uart:
  tx_pin: 1
  rx_pin: 3
  baud_rate: 9600

tuya:


switch:
  - platform: "tuya"
    name: "Power"
    switch_datapoint: 1
    restore_mode: RESTORE_DEFAULT_OFF


select:
  - platform: "tuya"
    id: fan_mode_select  
    name: "Fan mode"
    enum_datapoint: 4
    optimistic: false
    options:
      0: High
      1: Low

sensor:
  - platform: "tuya"
    name: "Humidity sensor"
    sensor_datapoint: 6
    device_class: "humidity"

  - platform: "tuya"
    name: "Humidity target"
    sensor_datapoint: 2
    device_class: "humidity"

binary_sensor:
  - platform: "tuya"
    name: "Water tank ok"
    sensor_datapoint: 25

text_sensor:
  - platform: wifi_info
    ip_address:
      name: ESP IP Address
    ssid:
      name: ESP Connected SSID
    bssid:
      name: ESP Connected BSSID
    mac_address:
      name: ESP Mac Wifi Address
